services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    container_name: sqlserver-2017
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - microstore-sqlserver:/var/opt/mssql

  redis:
    image : redis:7-alpine
    container_name: redis
    ports:
      - "27017:27017"
    volumes:
      - microstore-redis:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300